"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, CircleAlert, FileText, MapPin, Plus, UsersRound, WalletCards, X } from "lucide-react";
import { getProject, recordProjectUpdate } from "@/lib/data";
import { date, money, percent, statusLabel } from "@/lib/format";
import { AlignmentChart, ExecutionChart } from "./charts";

const tabs = ["Resumen", "Marco lógico", "Equipo", "Territorio", "Riesgos e hitos", "Evidencias"];

function Progress({ label, value, tone = "cyan" }) { return <div className="metric-progress"><div><span>{label}</span><strong>{percent(value)}</strong></div><div className={`progress-track progress-track--${tone}`}><span style={{ width: `${Math.min(100, Number(value || 0))}%` }}/></div></div>; }

export function Project360({ id }) {
  const [data, setData] = useState(null); const [tab, setTab] = useState("Resumen"); const [updateOpen, setUpdateOpen] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [now, setNow] = useState(null);
  useEffect(() => { getProject(id).then(setData); }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => setNow(Date.now()), 0); return () => window.clearTimeout(timer); }, []);
  const p = data?.project;
  const timeProgress = useMemo(() => { if (!p || !now) return 0; const start = new Date(p.start_date).getTime(); const end = new Date(p.end_date).getTime(); return Math.max(0, Math.min(100, (now - start) / (end - start) * 100)); }, [p, now]);
  const [form, setForm] = useState({ snapshot_date: new Date().toISOString().slice(0, 10), expenditure_amount: 0, commitments_amount: 0, planned_execution_amount: 0, physical_progress_pct: 0, summary: "", achievements: "", bottlenecks: "", next_steps: "", status: "active" });
function openUpdate() {
  setMessage("");
  setForm((current) => ({
    ...current,
    expenditure_amount: p?.spent || 0,
    commitments_amount: p?.commitments || 0,
    physical_progress_pct: p?.physical_progress_pct || 0,
    status: p?.status || "active",
  }));
  setUpdateOpen(true);
}
  async function saveUpdate() { setSaving(true); setMessage(""); try { await recordProjectUpdate(id, { ...form, budget_amount: p.budget_total, report_date: form.snapshot_date, expenditure_amount: Number(form.expenditure_amount), commitments_amount: Number(form.commitments_amount), planned_execution_amount: Number(form.planned_execution_amount), physical_progress_pct: Number(form.physical_progress_pct) }); setUpdateOpen(false); setData(await getProject(id)); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  if (!data || !p) return <div className="skeleton-panel">Cargando Ficha 360°…</div>;
  const projectForRadar = { ...p, time_progress_pct: timeProgress };
  return <div className="page-stack"><Link href="/projects" className="back-link"><ArrowLeft size={15}/> Volver a la cartera</Link><section className="project-hero" style={{ "--accent": p.primary_area_accent || "#69CFD8" }}><div><div className="hero-meta"><span className={`status status--${p.status}`}>{statusLabel[p.status]}</span><span>{p.code}</span><span>{p.primary_area_short_name}</span></div><h1>{p.acronym || p.title}</h1><p>{p.title}</p></div><button className="primary-button" onClick={openUpdate}><Plus size={16}/> Registrar corte</button></section><section className="project-facts"><div><WalletCards size={17}/><span>Presupuesto</span><strong>{money(p.budget_total)}</strong></div><div><CalendarDays size={17}/><span>Vigencia</span><strong>{date(p.start_date)} — {date(p.end_date)}</strong></div><div><UsersRound size={17}/><span>Equipo</span><strong>{p.staff_count || data.staff.length} asignaciones</strong></div><div><MapPin size={17}/><span>Territorio</span><strong>{(p.municipalities || data.locations.map((l) => l.municipality)).length} municipios</strong></div></section><nav className="tabs">{tabs.map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "Resumen" && <div className="dashboard-grid dashboard-grid--wide"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">ALINEAMIENTO</span><h2>Tiempo, recursos y resultados</h2></div></div><div className="alignment-layout"><div><Progress label="Tiempo consumido" value={timeProgress} tone="muted"/><Progress label="Ejecución financiera" value={p.execution_pct}/><Progress label="Avance físico" value={p.physical_progress_pct} tone="violet"/><Progress label="Utilización" value={p.utilization_pct} tone="gold"/></div><AlignmentChart project={projectForRadar}/></div></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">IDENTIDAD</span><h2>Datos del proyecto</h2></div></div><dl className="fact-list"><div><dt>Donante</dt><dd>{p.donor || "—"}</dd></div><div><dt>Coordinación</dt><dd>{p.coordinator || "—"}</dd></div><div><dt>Departamentos</dt><dd>{(p.departments || []).join(", ") || "—"}</dd></div><div><dt>Municipios</dt><dd>{(p.municipalities || []).join(", ") || "—"}</dd></div></dl><p className="summary-text">{p.summary}</p></article><article className="panel panel--chart span-2"><div className="panel-heading"><div><span className="eyebrow">HISTÓRICO</span><h2>Trayectoria financiera</h2></div></div><ExecutionChart rows={(data.snapshots || []).map((s) => ({ month_key: s.snapshot_date?.slice(0, 7), planned: s.planned_execution_amount, spent: s.expenditure_amount, commitments: s.commitments_amount }))}/></article><article className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">COMPONENTES</span><h2>Arquitectura operativa</h2></div></div><div className="component-grid">{data.components.map((c) => <div className="component-card" key={c.id}><span>{c.code}</span><h3>{c.title}</h3><p>{c.description}</p><Progress label="Avance" value={c.progress_pct}/></div>)}</div></article></div>}
    {tab === "Marco lógico" && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">RESULTS CHAIN</span><h2>Matriz de resultados e indicadores</h2></div></div><div className="results-tree">{data.results.map((r) => <div className="result-node" key={r.id}><div className="result-node-head"><span>{r.level}</span><strong>{r.code} · {r.title}</strong></div><p>{r.description}</p><div className="indicator-list">{data.indicators.filter((i) => i.result_id === r.id).map((i) => { const value = i.target_value ? Number(i.current_value || 0) / Number(i.target_value) * 100 : 0; return <div key={i.id}><span>{i.code}</span><div><strong>{i.name}</strong><small>{i.current_value ?? 0} / {i.target_value ?? "—"} {i.unit}</small></div><Progress label="Cumplimiento" value={value}/></div>; })}</div></div>)}</div></section>}
    {tab === "Equipo" && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">HUMAN RESOURCES</span><h2>Asignaciones al proyecto</h2></div></div><div className="people-grid">{data.staff.map((s) => <article key={s.id}><div className="avatar">{s.full_name?.split(" ").map((x) => x[0]).slice(0, 2).join("")}</div><div><strong>{s.full_name}</strong><span>{s.role_title || s.title}</span><small>{s.contract_type} · {s.allocation_pct}% de dedicación</small></div></article>)}</div></section>}
    {tab === "Territorio" && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">FIELD FOOTPRINT</span><h2>Intervenciones registradas</h2></div></div><div className="location-list">{data.locations.map((l) => <article key={l.id}><MapPin size={18}/><div><strong>{l.municipality || l.location_name}</strong><span>{l.department}</span><small>{l.intervention_type}</small></div><code>{Number(l.latitude).toFixed(4)}, {Number(l.longitude).toFixed(4)}</code></article>)}</div></section>}
    {tab === "Riesgos e hitos" && <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">RISK REGISTER</span><h2>Riesgos activos</h2></div></div><div className="risk-list">{data.risks.map((r) => <article key={r.id}><CircleAlert size={18}/><div><span className={`status status--${r.level === "critical" ? "critical" : "attention"}`}>{r.level}</span><h3>{r.title}</h3><p>{r.description}</p><small>Mitigación: {r.mitigation}</small></div></article>)}</div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">MILESTONES</span><h2>Próximos hitos</h2></div></div><div className="milestone-list">{data.milestones.map((m) => <article key={m.id}><time>{date(m.due_date)}</time><div><strong>{m.title}</strong><span>{m.responsible}</span></div></article>)}</div></section></div>}
    {tab === "Evidencias" && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">EVIDENCE VAULT</span><h2>Documentos y fotografías</h2></div></div>{data.assets.length ? <div className="asset-grid">{data.assets.map((a) => <a href={a.external_url} target="_blank" rel="noreferrer" key={a.id}><FileText size={20}/><div><strong>{a.title}</strong><span>{a.asset_type}</span></div></a>)}</div> : <div className="empty-state"><FileText size={30}/><strong>Sin evidencias registradas</strong><p>Los archivos cargados desde el formulario aparecerán en esta sección.</p></div>}</section>}
    {updateOpen && <div className="modal-backdrop"><div className="drawer"><div className="drawer-head"><div><span className="eyebrow">NEW SNAPSHOT</span><h2>Registrar corte periódico</h2></div><button onClick={() => setUpdateOpen(false)}><X size={18}/></button></div><div className="form-grid"><label className="field"><span>Fecha de corte</span><input type="date" value={form.snapshot_date} onChange={(e) => setForm({ ...form, snapshot_date: e.target.value })}/></label><label className="field"><span>Estado</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="active">En curso</option><option value="attention">Atención</option><option value="critical">Crítico</option><option value="closing">En cierre</option><option value="closed">Cerrado</option></select></label><label className="field"><span>Gasto acumulado</span><input type="number" value={form.expenditure_amount} onChange={(e) => setForm({ ...form, expenditure_amount: e.target.value })}/></label><label className="field"><span>Compromisos</span><input type="number" value={form.commitments_amount} onChange={(e) => setForm({ ...form, commitments_amount: e.target.value })}/></label><label className="field"><span>Avance físico %</span><input type="number" min="0" max="100" value={form.physical_progress_pct} onChange={(e) => setForm({ ...form, physical_progress_pct: e.target.value })}/></label><label className="field field--wide"><span>Resumen del período</span><textarea value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })}/></label><label className="field field--wide"><span>Principales logros</span><textarea value={form.achievements} onChange={(e) => setForm({ ...form, achievements: e.target.value })}/></label><label className="field field--wide"><span>Cuellos de botella</span><textarea value={form.bottlenecks} onChange={(e) => setForm({ ...form, bottlenecks: e.target.value })}/></label><label className="field field--wide"><span>Próximos pasos</span><textarea value={form.next_steps} onChange={(e) => setForm({ ...form, next_steps: e.target.value })}/></label></div>{message && <div className="form-error">{message}</div>}<button className="primary-button full-button" disabled={saving} onClick={saveUpdate}>{saving ? "Guardando…" : "Guardar corte"}</button></div></div>}
  </div>;
}
