"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Grid2X2, List, Plus, Search, SlidersHorizontal } from "lucide-react";
import { getAreas, getProjects } from "@/lib/data";
import { date, money, percent, statusLabel } from "@/lib/format";

export function ProjectsView() {
  const [projects, setProjects] = useState([]); const [areas, setAreas] = useState([]); const [query, setQuery] = useState(""); const [area, setArea] = useState("all"); const [status, setStatus] = useState("all"); const [view, setView] = useState("grid");
  useEffect(() => { Promise.all([getProjects(), getAreas()]).then(([p, a]) => { setProjects(p); setAreas(a); }); }, []);
  const filtered = useMemo(() => projects.filter((p) => { const haystack = [p.title, p.acronym, p.code, p.donor, p.coordinator, ...(p.municipalities || [])].join(" ").toLowerCase(); return haystack.includes(query.toLowerCase()) && (area === "all" || p.primary_area_slug === area) && (status === "all" || p.status === status); }), [projects, query, area, status]);
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">PROJECT PORTFOLIO</span><h1>Cartera de proyectos</h1><p>Explore, filtre y abra la ficha integral de cada intervención.</p></div><Link href="/projects/new" className="primary-button"><Plus size={17}/> Agregar proyecto</Link></section>
    <section className="filter-bar"><label className="search-box"><Search size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar proyecto, código, donante, coordinador o municipio"/></label><label><SlidersHorizontal size={16}/><select value={area} onChange={(e) => setArea(e.target.value)}><option value="all">Todas las áreas</option>{areas.map((a) => <option key={a.id} value={a.slug}>{a.name}</option>)}</select></label><label><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todos los estados</option><option value="active">En curso</option><option value="attention">Atención</option><option value="critical">Crítico</option><option value="closing">En cierre</option><option value="closed">Cerrado</option></select></label><div className="view-switch"><button className={view === "grid" ? "active" : ""} onClick={() => setView("grid")}><Grid2X2 size={16}/></button><button className={view === "table" ? "active" : ""} onClick={() => setView("table")}><List size={16}/></button></div></section>
    <div className="result-count"><strong>{filtered.length}</strong> proyectos encontrados</div>
    {view === "grid" ? <section className="project-grid">{filtered.map((p) => <Link href={`/project?id=${p.id}`} className="project-card" key={p.id} style={{ "--accent": p.primary_area_accent || "#69CFD8" }}><div className="project-card-head"><span className={`status status--${p.status}`}>{statusLabel[p.status]}</span><ArrowUpRight size={17}/></div><span className="project-code">{p.code}</span><h2>{p.acronym}</h2><p>{p.title}</p><div className="project-card-kpis"><div><span>Presupuesto</span><strong>{money(p.budget_total)}</strong></div><div><span>Ejecución</span><strong>{percent(p.execution_pct)}</strong></div><div><span>Avance</span><strong>{percent(p.physical_progress_pct)}</strong></div><div><span>RRHH</span><strong>{p.staff_count || 0}</strong></div></div><div className="progress-track"><span style={{ width: `${Math.min(100, p.physical_progress_pct || 0)}%` }}/></div><div className="project-card-foot"><span>{p.primary_area_short_name}</span><span>{(p.municipalities || []).length} municipios</span><span>{date(p.end_date)}</span></div></Link>)}</section> : <section className="panel table-wrap"><table className="data-table"><thead><tr><th>Proyecto</th><th>Área</th><th>Donante</th><th>Presupuesto</th><th>Ejecución</th><th>Avance</th><th>RRHH</th><th>Estado</th></tr></thead><tbody>{filtered.map((p) => <tr key={p.id}><td><Link href={`/project?id=${p.id}`}><strong>{p.acronym}</strong><span>{p.code}</span></Link></td><td>{p.primary_area_short_name}</td><td>{p.donor}</td><td>{money(p.budget_total)}</td><td>{percent(p.execution_pct)}</td><td>{percent(p.physical_progress_pct)}</td><td>{p.staff_count}</td><td><span className={`status status--${p.status}`}>{statusLabel[p.status]}</span></td></tr>)}</tbody></table></section>}
  </div>;
}
