"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, FileUp, MapPin, Plus, Trash2 } from "lucide-react";
import { createProjectBundle, getAreas, uploadProjectAssets } from "@/lib/data";
import { LocationPicker } from "./location-picker";

const emptyComponent = () => ({ code: "", title: "", description: "", budget_allocated: 0, progress_pct: 0 });
const emptyIndicator = () => ({ code: "", name: "", unit: "personas", baseline_value: 0, target_value: 0, current_value: 0, frequency: "quarterly", data_source: "" });
const emptyResult = () => ({ temp_id: crypto.randomUUID(), code: "", level: "outcome", title: "", description: "", parent_temp_id: null, indicators: [emptyIndicator()] });
const emptyLocation = () => ({ geometry_type: "point", department: "", municipality: "", location_name: "", latitude: 14.0723, longitude: -87.2068, intervention_type: "", notes: "" });
const emptyStaff = () => ({ full_name: "", email: "", title: "", contract_type: "Proyecto", role_title: "", allocation_pct: 100 });

export function ProjectForm() {
  const router = useRouter(); const [areas, setAreas] = useState([]); const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [files, setFiles] = useState([]);
  const [project, setProject] = useState({ code: "", acronym: "", title: "", summary: "", donor: "", coordinator: "", start_date: "", end_date: "", currency: "USD", budget_total: 0, status: "draft", country: "Honduras", is_demo: false });
  const [areaId, setAreaId] = useState(1); const [financial, setFinancial] = useState({ snapshot_date: new Date().toISOString().slice(0, 10), budget_amount: 0, planned_execution_amount: 0, expenditure_amount: 0, commitments_amount: 0, notes: "Registro inicial" });
  const [components, setComponents] = useState([emptyComponent()]); const [results, setResults] = useState([emptyResult()]); const [locations, setLocations] = useState([emptyLocation()]); const [staff, setStaff] = useState([emptyStaff()]);
  useEffect(() => { getAreas().then((rows) => { setAreas(rows); if (rows[0]) setAreaId(rows[0].id); }); }, []);
  const steps = ["Identidad", "Recursos", "Marco lógico", "Territorio", "Equipo y evidencias"];
  const canContinue = useMemo(() => step === 0 ? project.code && project.title && project.start_date && project.end_date : true, [step, project]);
  const updateRow = (setter, rows, index, patch) => setter(rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  async function submit() { setBusy(true); setMessage(""); try { const payload = { project: { ...project, budget_total: Number(project.budget_total || 0) }, areas: [{ area_id: Number(areaId), is_primary: true, contribution_pct: 100 }], components: components.filter((c) => c.title).map((c, i) => ({ ...c, code: c.code || `C${i + 1}`, budget_allocated: Number(c.budget_allocated || 0), sort_order: i + 1 })), results: results.filter((r) => r.title).map((r, i) => ({ ...r, code: r.code || `R${i + 1}`, sort_order: i + 1, indicators: r.indicators.filter((ind) => ind.name).map((ind, j) => ({ ...ind, code: ind.code || `IND-${i + 1}.${j + 1}`, baseline_value: Number(ind.baseline_value || 0), target_value: Number(ind.target_value || 0), current_value: Number(ind.current_value || 0) })) })), locations: locations.filter((l) => l.municipality || (l.latitude && l.longitude)).map((l) => ({ ...l, latitude: Number(l.latitude), longitude: Number(l.longitude) })), staff: staff.filter((s) => s.full_name).map((s) => ({ ...s, allocation_pct: Number(s.allocation_pct || 0) })), financial: { ...financial, budget_amount: Number(project.budget_total || 0), planned_execution_amount: Number(financial.planned_execution_amount || 0), expenditure_amount: Number(financial.expenditure_amount || 0), commitments_amount: Number(financial.commitments_amount || 0) }, update: { report_date: financial.snapshot_date, physical_progress_pct: 0, summary: "Registro inicial del proyecto", achievements: "", bottlenecks: "", next_steps: "Completar línea base y primer corte de seguimiento." } }; const id = await createProjectBundle(payload); await uploadProjectAssets(id, files); router.push(`/project?id=${id}`); } catch (error) { setMessage(error.message || "No fue posible registrar el proyecto."); } finally { setBusy(false); } }
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">STRUCTURED PROJECT INTAKE</span><h1>Agregar un proyecto</h1><p>Registro progresivo y homogéneo para la cartera de FAO Honduras.</p></div></section><section className="wizard"><ol className="stepper">{steps.map((label, index) => <li key={label} className={index === step ? "active" : index < step ? "done" : ""}><span>{index < step ? <Check size={14}/> : index + 1}</span><small>{label}</small></li>)}</ol><div className="wizard-body">
    {step === 0 && <div className="form-section"><div className="section-title"><span>01</span><div><h2>Identidad y alineamiento</h2><p>Información corporativa básica y área programática principal.</p></div></div><div className="form-grid"><label className="field"><span>Código *</span><input value={project.code} onChange={(e) => setProject({ ...project, code: e.target.value })} placeholder="GCP/HON/000/XXX"/></label><label className="field"><span>Acrónimo</span><input value={project.acronym} onChange={(e) => setProject({ ...project, acronym: e.target.value })} placeholder="RECOVER"/></label><label className="field field--wide"><span>Nombre completo *</span><input value={project.title} onChange={(e) => setProject({ ...project, title: e.target.value })}/></label><label className="field field--wide"><span>Resumen</span><textarea value={project.summary} onChange={(e) => setProject({ ...project, summary: e.target.value })}/></label><label className="field"><span>Área principal</span><select value={areaId} onChange={(e) => setAreaId(e.target.value)}>{areas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="field"><span>Estado</span><select value={project.status} onChange={(e) => setProject({ ...project, status: e.target.value })}><option value="draft">Borrador</option><option value="active">En curso</option><option value="attention">Atención</option><option value="critical">Crítico</option><option value="closing">En cierre</option></select></label><label className="field"><span>Donante</span><input value={project.donor} onChange={(e) => setProject({ ...project, donor: e.target.value })}/></label><label className="field"><span>Coordinación</span><input value={project.coordinator} onChange={(e) => setProject({ ...project, coordinator: e.target.value })}/></label><label className="field"><span>Fecha de inicio *</span><input type="date" value={project.start_date} onChange={(e) => setProject({ ...project, start_date: e.target.value })}/></label><label className="field"><span>Fecha de cierre *</span><input type="date" value={project.end_date} onChange={(e) => setProject({ ...project, end_date: e.target.value })}/></label></div></div>}
    {step === 1 && <div className="form-section"><div className="section-title"><span>02</span><div><h2>Recursos y componentes</h2><p>Presupuesto, punto de partida financiero y estructura técnica.</p></div></div><div className="form-grid"><label className="field"><span>Presupuesto total (USD)</span><input type="number" value={project.budget_total} onChange={(e) => setProject({ ...project, budget_total: e.target.value })}/></label><label className="field"><span>Gasto a la fecha</span><input type="number" value={financial.expenditure_amount} onChange={(e) => setFinancial({ ...financial, expenditure_amount: e.target.value })}/></label><label className="field"><span>Compromisos</span><input type="number" value={financial.commitments_amount} onChange={(e) => setFinancial({ ...financial, commitments_amount: e.target.value })}/></label><label className="field"><span>Fecha de corte</span><input type="date" value={financial.snapshot_date} onChange={(e) => setFinancial({ ...financial, snapshot_date: e.target.value })}/></label></div><div className="repeat-list">{components.map((row, index) => <div className="repeat-card" key={index}><div className="repeat-card-head"><strong>Componente {index + 1}</strong>{components.length > 1 && <button onClick={() => setComponents(components.filter((_, i) => i !== index))}><Trash2 size={15}/></button>}</div><div className="form-grid"><label className="field"><span>Código</span><input value={row.code} onChange={(e) => updateRow(setComponents, components, index, { code: e.target.value })}/></label><label className="field field--grow"><span>Título</span><input value={row.title} onChange={(e) => updateRow(setComponents, components, index, { title: e.target.value })}/></label><label className="field field--wide"><span>Descripción</span><textarea value={row.description} onChange={(e) => updateRow(setComponents, components, index, { description: e.target.value })}/></label></div></div>)}<button className="secondary-button" onClick={() => setComponents([...components, emptyComponent()])}><Plus size={16}/> Agregar componente</button></div></div>}
    {step === 2 && <div className="form-section"><div className="section-title"><span>03</span><div><h2>Marco lógico</h2><p>Resultados e indicadores estandarizados con línea base y meta.</p></div></div><div className="repeat-list">{results.map((row, index) => <div className="repeat-card" key={row.temp_id}><div className="repeat-card-head"><strong>Resultado {index + 1}</strong>{results.length > 1 && <button onClick={() => setResults(results.filter((_, i) => i !== index))}><Trash2 size={15}/></button>}</div><div className="form-grid"><label className="field"><span>Nivel</span><select value={row.level} onChange={(e) => updateRow(setResults, results, index, { level: e.target.value })}><option value="impact">Impacto</option><option value="outcome">Outcome</option><option value="output">Output</option></select></label><label className="field"><span>Código</span><input value={row.code} onChange={(e) => updateRow(setResults, results, index, { code: e.target.value })}/></label><label className="field field--wide"><span>Título</span><input value={row.title} onChange={(e) => updateRow(setResults, results, index, { title: e.target.value })}/></label></div>{row.indicators.map((ind, indIndex) => <div className="indicator-row" key={indIndex}><input value={ind.code} onChange={(e) => { const indicators = row.indicators.map((item, i) => i === indIndex ? { ...item, code: e.target.value } : item); updateRow(setResults, results, index, { indicators }); }} placeholder="Código"/><input value={ind.name} onChange={(e) => { const indicators = row.indicators.map((item, i) => i === indIndex ? { ...item, name: e.target.value } : item); updateRow(setResults, results, index, { indicators }); }} placeholder="Indicador"/><input value={ind.unit} onChange={(e) => { const indicators = row.indicators.map((item, i) => i === indIndex ? { ...item, unit: e.target.value } : item); updateRow(setResults, results, index, { indicators }); }} placeholder="Unidad"/><input type="number" value={ind.baseline_value} onChange={(e) => { const indicators = row.indicators.map((item, i) => i === indIndex ? { ...item, baseline_value: e.target.value } : item); updateRow(setResults, results, index, { indicators }); }} placeholder="Línea base"/><input type="number" value={ind.target_value} onChange={(e) => { const indicators = row.indicators.map((item, i) => i === indIndex ? { ...item, target_value: e.target.value } : item); updateRow(setResults, results, index, { indicators }); }} placeholder="Meta"/></div>)}</div>)}<button className="secondary-button" onClick={() => setResults([...results, emptyResult()])}><Plus size={16}/> Agregar resultado</button></div></div>}
    {step === 3 && <div className="form-section"><div className="section-title"><span>04</span><div><h2>Territorio</h2><p>Registre puntos de intervención; posteriormente podrán incorporarse polígonos y corredores.</p></div></div>{locations.map((row, index) => <div className="location-editor" key={index}><LocationPicker value={row} onChange={(coords) => updateRow(setLocations, locations, index, coords)}/><div className="form-grid"><label className="field"><span>Departamento</span><input value={row.department} onChange={(e) => updateRow(setLocations, locations, index, { department: e.target.value })}/></label><label className="field"><span>Municipio</span><input value={row.municipality} onChange={(e) => updateRow(setLocations, locations, index, { municipality: e.target.value })}/></label><label className="field"><span>Latitud</span><input type="number" step="any" value={row.latitude} onChange={(e) => updateRow(setLocations, locations, index, { latitude: e.target.value })}/></label><label className="field"><span>Longitud</span><input type="number" step="any" value={row.longitude} onChange={(e) => updateRow(setLocations, locations, index, { longitude: e.target.value })}/></label><label className="field field--wide"><span>Tipo de intervención</span><input value={row.intervention_type} onChange={(e) => updateRow(setLocations, locations, index, { intervention_type: e.target.value })}/></label></div></div>)}<button className="secondary-button" onClick={() => setLocations([...locations, emptyLocation()])}><MapPin size={16}/> Agregar ubicación</button></div>}
    {step === 4 && <div className="form-section"><div className="section-title"><span>05</span><div><h2>Equipo y evidencias</h2><p>Asignaciones de RRHH y archivos iniciales del proyecto.</p></div></div><div className="repeat-list">{staff.map((row, index) => <div className="repeat-card" key={index}><div className="form-grid"><label className="field"><span>Nombre</span><input value={row.full_name} onChange={(e) => updateRow(setStaff, staff, index, { full_name: e.target.value })}/></label><label className="field"><span>Rol en el proyecto</span><input value={row.role_title} onChange={(e) => updateRow(setStaff, staff, index, { role_title: e.target.value })}/></label><label className="field"><span>Correo</span><input type="email" value={row.email} onChange={(e) => updateRow(setStaff, staff, index, { email: e.target.value })}/></label><label className="field"><span>Dedicación %</span><input type="number" min="0" max="100" value={row.allocation_pct} onChange={(e) => updateRow(setStaff, staff, index, { allocation_pct: e.target.value })}/></label></div></div>)}<button className="secondary-button" onClick={() => setStaff([...staff, emptyStaff()])}><Plus size={16}/> Agregar persona</button></div><label className="file-drop"><FileUp size={28}/><strong>Fotografías y documentos</strong><span>PDF, imágenes, Word, Excel, CSV o GeoJSON · máximo 25 MB por archivo</span><input type="file" multiple onChange={(e) => setFiles([...e.target.files])}/><small>{files.length ? `${files.length} archivo(s) seleccionado(s)` : "Seleccionar archivos"}</small></label><div className="review-box"><strong>Antes de registrar</strong><p>El presupuesto se contará una sola vez bajo el área principal. Las ubicaciones mostrarán presencia territorial, no una distribución automática del presupuesto.</p></div></div>}
    {message && <div className="form-error">{message}</div>}<div className="wizard-actions"><button className="secondary-button" disabled={step === 0 || busy} onClick={() => setStep(step - 1)}><ArrowLeft size={16}/> Anterior</button>{step < steps.length - 1 ? <button className="primary-button" disabled={!canContinue} onClick={() => setStep(step + 1)}>Continuar <ArrowRight size={16}/></button> : <button className="primary-button" disabled={busy} onClick={submit}>{busy ? "Registrando…" : "Registrar proyecto"} <Check size={16}/></button>}</div></div></section></div>;
}
