-- Acceso abierto solo para prototipo. No cargar información oficial o sensible bajo este modelo.
do $$ declare t text; begin foreach t in array array['portfolio_programmatic_areas','portfolio_projects','portfolio_project_programmatic_areas','portfolio_project_components','portfolio_results','portfolio_indicators','portfolio_staff_members','portfolio_project_staff','portfolio_project_locations','portfolio_financial_snapshots','portfolio_project_updates','portfolio_risks','portfolio_project_milestones','portfolio_project_assets'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists "MVP read %s" on public.%I',t,t); execute format('create policy "MVP read %s" on public.%I for select to anon,authenticated using (true)',t,t); execute format('drop policy if exists "MVP insert %s" on public.%I',t,t); execute format('create policy "MVP insert %s" on public.%I for insert to anon,authenticated with check (true)',t,t); execute format('drop policy if exists "MVP update %s" on public.%I',t,t); execute format('create policy "MVP update %s" on public.%I for update to anon,authenticated using (true) with check (true)',t,t); end loop; end $$;
grant usage on schema public to anon,authenticated;
grant select,insert,update on all tables in schema public to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;
grant execute on function public.portfolio_create_project_bundle(jsonb) to anon,authenticated;
grant execute on function public.portfolio_record_project_update(uuid,jsonb) to anon,authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('portfolio-assets','portfolio-assets',true,26214400,array['image/jpeg','image/png','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv','application/geo+json','application/zip']) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "MVP public read portfolio assets" on storage.objects; create policy "MVP public read portfolio assets" on storage.objects for select to anon,authenticated using(bucket_id='portfolio-assets');
drop policy if exists "MVP public insert portfolio assets" on storage.objects; create policy "MVP public insert portfolio assets" on storage.objects for insert to anon,authenticated with check(bucket_id='portfolio-assets');
