-- Contrato reproducible del MVP. La instancia conectada ya contiene una versión ampliada.
create extension if not exists pgcrypto;
create extension if not exists postgis;

do $$ begin create type public.portfolio_project_status as enum ('draft','active','attention','critical','closing','closed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.portfolio_result_level as enum ('impact','outcome','output'); exception when duplicate_object then null; end $$;
do $$ begin create type public.portfolio_indicator_status as enum ('not_started','on_track','attention','off_track','achieved'); exception when duplicate_object then null; end $$;
do $$ begin create type public.portfolio_location_geometry_type as enum ('point','municipality','polygon','corridor','landscape','other'); exception when duplicate_object then null; end $$;
do $$ begin create type public.portfolio_asset_type as enum ('document','photo','map','dataset','link','other'); exception when duplicate_object then null; end $$;
do $$ begin create type public.portfolio_risk_level as enum ('low','medium','high','critical'); exception when duplicate_object then null; end $$;

create table if not exists public.portfolio_programmatic_areas (id smallserial primary key, code text unique not null, slug text unique not null, name text not null, short_name text not null, description text not null default '', accent text not null default '#69CFD8', sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.portfolio_projects (id uuid primary key default gen_random_uuid(), code text unique not null, acronym text not null default '', title text not null, summary text not null default '', country text not null default 'Honduras', donor text not null default '', coordinator text not null default '', start_date date not null, end_date date not null, currency text not null default 'USD', budget_total numeric(18,2) not null default 0, status public.portfolio_project_status not null default 'draft', is_demo boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (end_date >= start_date));
create table if not exists public.portfolio_project_programmatic_areas (project_id uuid references public.portfolio_projects on delete cascade, area_id smallint references public.portfolio_programmatic_areas, is_primary boolean not null default false, contribution_pct numeric(5,2) not null default 0, created_at timestamptz not null default now(), primary key(project_id,area_id));
create unique index if not exists portfolio_one_primary_area on public.portfolio_project_programmatic_areas(project_id) where is_primary;
create table if not exists public.portfolio_project_components (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, code text not null, title text not null, description text not null default '', budget_allocated numeric(18,2) not null default 0, progress_pct numeric(5,2) not null default 0, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.portfolio_results (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, parent_result_id uuid references public.portfolio_results on delete set null, code text not null, level public.portfolio_result_level not null, title text not null, description text not null default '', sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.portfolio_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, result_id uuid not null references public.portfolio_results on delete cascade, code text not null, name text not null, definition text not null default '', unit text not null default '', baseline_value numeric, target_value numeric, current_value numeric, direction text not null default 'increase', frequency text not null default 'quarterly', data_source text not null default '', status public.portfolio_indicator_status not null default 'not_started', last_measured_at date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.portfolio_staff_members (id uuid primary key default gen_random_uuid(), full_name text not null, email text not null default '', title text not null default '', contract_type text not null default '', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists portfolio_staff_email_unique on public.portfolio_staff_members(lower(email)) where email <> '';
create table if not exists public.portfolio_project_staff (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, staff_id uuid not null references public.portfolio_staff_members, role_title text not null, allocation_pct numeric(5,2) not null default 100, start_date date, end_date date, created_at timestamptz not null default now());
create table if not exists public.portfolio_project_locations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, geometry_type public.portfolio_location_geometry_type not null default 'point', department text not null default '', municipality text not null default '', municipality_code text not null default '', location_name text not null default '', intervention_type text not null default '', latitude double precision, longitude double precision, geom geometry(Geometry,4326), notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists portfolio_locations_geom_gix on public.portfolio_project_locations using gist(geom);
create table if not exists public.portfolio_financial_snapshots (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, snapshot_date date not null, budget_amount numeric(18,2) not null default 0, planned_execution_amount numeric(18,2) not null default 0, expenditure_amount numeric(18,2) not null default 0, commitments_amount numeric(18,2) not null default 0, notes text not null default '', created_at timestamptz not null default now(), unique(project_id,snapshot_date));
create table if not exists public.portfolio_project_updates (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, report_date date not null, physical_progress_pct numeric(5,2) not null default 0, summary text not null default '', achievements text not null default '', bottlenecks text not null default '', next_steps text not null default '', created_at timestamptz not null default now(), unique(project_id,report_date));
create table if not exists public.portfolio_risks (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, title text not null, description text not null default '', level public.portfolio_risk_level not null default 'medium', probability int not null default 1, impact int not null default 1, mitigation text not null default '', owner text not null default '', status text not null default 'open', due_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.portfolio_project_milestones (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, title text not null, milestone_type text not null default '', due_date date not null, status text not null default 'planned', responsible text not null default '', completed_at date, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.portfolio_project_assets (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.portfolio_projects on delete cascade, asset_type public.portfolio_asset_type not null default 'document', title text not null, description text not null default '', storage_bucket text not null default 'portfolio-assets', storage_path text not null, external_url text not null default '', file_name text not null default '', mime_type text not null default '', size_bytes bigint not null default 0, latitude double precision, longitude double precision, captured_at timestamptz, created_at timestamptz not null default now());

insert into public.portfolio_programmatic_areas(code,slug,name,short_name,accent,sort_order) values ('BP','produccion','Mejor Producción','Producción','#72D6C9',1),('BN','nutricion','Mejor Nutrición','Nutrición','#E5B86B',2),('BE','ambiente','Mejor Ambiente','Ambiente','#77B5E8',3),('BL','vida','Mejor Vida','Vida','#A99BE7',4) on conflict(code) do update set slug=excluded.slug,name=excluded.name,short_name=excluded.short_name,accent=excluded.accent;
