create or replace view public.portfolio_latest_financial with (security_invoker=true) as select distinct on (project_id) * from public.portfolio_financial_snapshots order by project_id,snapshot_date desc,created_at desc;
create or replace view public.portfolio_latest_update with (security_invoker=true) as select distinct on (project_id) * from public.portfolio_project_updates order by project_id,report_date desc,created_at desc;
create or replace view public.portfolio_project_staff_v with (security_invoker=true) as select ps.*,s.full_name,s.email,s.title,s.contract_type,s.active from public.portfolio_project_staff ps join public.portfolio_staff_members s on s.id=ps.staff_id;
create or replace view public.portfolio_project_locations_v with (security_invoker=true) as select l.*,p.code project_code,p.acronym project_acronym,p.title project_title,a.slug area_slug,case when l.geom is null then null else st_asgeojson(l.geom)::jsonb end geometry from public.portfolio_project_locations l join public.portfolio_projects p on p.id=l.project_id left join public.portfolio_project_programmatic_areas ppa on ppa.project_id=p.id and ppa.is_primary left join public.portfolio_programmatic_areas a on a.id=ppa.area_id;
create or replace view public.portfolio_project_summary with (security_invoker=true) as
select p.*,a.id primary_area_id,a.slug primary_area_slug,a.name primary_area_name,a.short_name primary_area_short_name,a.accent primary_area_accent,coalesce(f.expenditure_amount,0) spent,coalesce(f.commitments_amount,0) commitments,f.snapshot_date data_cutoff,case when p.budget_total>0 then round(coalesce(f.expenditure_amount,0)/p.budget_total*100,2) else 0 end execution_pct,case when p.budget_total>0 then round((coalesce(f.expenditure_amount,0)+coalesce(f.commitments_amount,0))/p.budget_total*100,2) else 0 end utilization_pct,coalesce(u.physical_progress_pct,0) physical_progress_pct,(select count(*) from public.portfolio_project_staff ps where ps.project_id=p.id) staff_count,(select count(*) from public.portfolio_project_components c where c.project_id=p.id) component_count,(select count(*) from public.portfolio_indicators i where i.project_id=p.id) indicator_count,(select array_agg(distinct l.department) filter(where l.department<>'') from public.portfolio_project_locations l where l.project_id=p.id) departments,(select array_agg(distinct l.municipality) filter(where l.municipality<>'') from public.portfolio_project_locations l where l.project_id=p.id) municipalities
from public.portfolio_projects p left join public.portfolio_project_programmatic_areas ppa on ppa.project_id=p.id and ppa.is_primary left join public.portfolio_programmatic_areas a on a.id=ppa.area_id left join public.portfolio_latest_financial f on f.project_id=p.id left join public.portfolio_latest_update u on u.project_id=p.id;
create or replace view public.portfolio_area_summary with (security_invoker=true) as select a.*,count(p.id) project_count,coalesce(sum(p.budget_total),0) total_budget,coalesce(sum(p.spent),0) spent,coalesce(sum(p.staff_count),0) staff_count,case when sum(p.budget_total)>0 then round(sum(p.spent)/sum(p.budget_total)*100,2) else 0 end execution_pct,coalesce(round(avg(p.physical_progress_pct),2),0) physical_progress_pct from public.portfolio_programmatic_areas a left join public.portfolio_project_summary p on p.primary_area_id=a.id group by a.id;
create or replace view public.portfolio_monthly_execution with (security_invoker=true) as select to_char(snapshot_date,'YYYY-MM') month_key,to_char(snapshot_date,'Mon YYYY') month_label,sum(planned_execution_amount) planned,sum(expenditure_amount) spent,sum(commitments_amount) commitments from public.portfolio_financial_snapshots group by 1,2 order by 1;

create or replace function public.portfolio_create_project_bundle(payload jsonb) returns uuid language plpgsql security invoker set search_path=public as $$
declare v_project_id uuid; v_result_id uuid; v_staff_id uuid; area jsonb; component jsonb; result_row jsonb; indicator_row jsonb; location_row jsonb; staff_row jsonb;
begin
  insert into public.portfolio_projects(code,acronym,title,summary,country,donor,coordinator,start_date,end_date,currency,budget_total,status,is_demo)
  values(payload->'project'->>'code',coalesce(payload->'project'->>'acronym',''),payload->'project'->>'title',coalesce(payload->'project'->>'summary',''),coalesce(payload->'project'->>'country','Honduras'),coalesce(payload->'project'->>'donor',''),coalesce(payload->'project'->>'coordinator',''),(payload->'project'->>'start_date')::date,(payload->'project'->>'end_date')::date,coalesce(payload->'project'->>'currency','USD'),coalesce((payload->'project'->>'budget_total')::numeric,0),coalesce((payload->'project'->>'status')::public.portfolio_project_status,'draft'),coalesce((payload->'project'->>'is_demo')::boolean,false)) returning id into v_project_id;
  for area in select * from jsonb_array_elements(coalesce(payload->'areas','[]'::jsonb)) loop insert into public.portfolio_project_programmatic_areas(project_id,area_id,is_primary,contribution_pct) values(v_project_id,(area->>'area_id')::smallint,coalesce((area->>'is_primary')::boolean,false),coalesce((area->>'contribution_pct')::numeric,0)); end loop;
  for component in select * from jsonb_array_elements(coalesce(payload->'components','[]'::jsonb)) loop insert into public.portfolio_project_components(project_id,code,title,description,budget_allocated,progress_pct,sort_order) values(v_project_id,component->>'code',component->>'title',coalesce(component->>'description',''),coalesce((component->>'budget_allocated')::numeric,0),coalesce((component->>'progress_pct')::numeric,0),coalesce((component->>'sort_order')::int,0)); end loop;
  for result_row in select * from jsonb_array_elements(coalesce(payload->'results','[]'::jsonb)) loop insert into public.portfolio_results(project_id,code,level,title,description,sort_order) values(v_project_id,result_row->>'code',(result_row->>'level')::public.portfolio_result_level,result_row->>'title',coalesce(result_row->>'description',''),coalesce((result_row->>'sort_order')::int,0)) returning id into v_result_id; for indicator_row in select * from jsonb_array_elements(coalesce(result_row->'indicators','[]'::jsonb)) loop insert into public.portfolio_indicators(project_id,result_id,code,name,definition,unit,baseline_value,target_value,current_value,frequency,data_source) values(v_project_id,v_result_id,indicator_row->>'code',indicator_row->>'name',coalesce(indicator_row->>'definition',''),coalesce(indicator_row->>'unit',''),nullif(indicator_row->>'baseline_value','')::numeric,nullif(indicator_row->>'target_value','')::numeric,nullif(indicator_row->>'current_value','')::numeric,coalesce(indicator_row->>'frequency','quarterly'),coalesce(indicator_row->>'data_source','')); end loop; end loop;
  for location_row in select * from jsonb_array_elements(coalesce(payload->'locations','[]'::jsonb)) loop insert into public.portfolio_project_locations(project_id,geometry_type,department,municipality,location_name,intervention_type,latitude,longitude,geom,notes) values(v_project_id,coalesce((location_row->>'geometry_type')::public.portfolio_location_geometry_type,'point'),coalesce(location_row->>'department',''),coalesce(location_row->>'municipality',''),coalesce(location_row->>'location_name',''),coalesce(location_row->>'intervention_type',''),nullif(location_row->>'latitude','')::double precision,nullif(location_row->>'longitude','')::double precision,case when nullif(location_row->>'latitude','') is not null and nullif(location_row->>'longitude','') is not null then st_setsrid(st_makepoint((location_row->>'longitude')::double precision,(location_row->>'latitude')::double precision),4326) else null end,coalesce(location_row->>'notes','')); end loop;
  for staff_row in select * from jsonb_array_elements(coalesce(payload->'staff','[]'::jsonb)) loop select id into v_staff_id from public.portfolio_staff_members where (staff_row->>'email')<>'' and lower(email)=lower(staff_row->>'email') limit 1; if v_staff_id is null then insert into public.portfolio_staff_members(full_name,email,title,contract_type) values(staff_row->>'full_name',coalesce(staff_row->>'email',''),coalesce(staff_row->>'title',''),coalesce(staff_row->>'contract_type','')) returning id into v_staff_id; end if; insert into public.portfolio_project_staff(project_id,staff_id,role_title,allocation_pct) values(v_project_id,v_staff_id,coalesce(staff_row->>'role_title',''),coalesce((staff_row->>'allocation_pct')::numeric,100)); v_staff_id:=null; end loop;
  if payload ? 'financial' then insert into public.portfolio_financial_snapshots(project_id,snapshot_date,budget_amount,planned_execution_amount,expenditure_amount,commitments_amount,notes) values(v_project_id,(payload->'financial'->>'snapshot_date')::date,coalesce((payload->'financial'->>'budget_amount')::numeric,0),coalesce((payload->'financial'->>'planned_execution_amount')::numeric,0),coalesce((payload->'financial'->>'expenditure_amount')::numeric,0),coalesce((payload->'financial'->>'commitments_amount')::numeric,0),coalesce(payload->'financial'->>'notes','')); end if;
  if payload ? 'update' then insert into public.portfolio_project_updates(project_id,report_date,physical_progress_pct,summary,achievements,bottlenecks,next_steps) values(v_project_id,(payload->'update'->>'report_date')::date,coalesce((payload->'update'->>'physical_progress_pct')::numeric,0),coalesce(payload->'update'->>'summary',''),coalesce(payload->'update'->>'achievements',''),coalesce(payload->'update'->>'bottlenecks',''),coalesce(payload->'update'->>'next_steps','')); end if;
  return v_project_id;
end $$;

create or replace function public.portfolio_record_project_update(target_project_id uuid,payload jsonb) returns void language plpgsql security invoker set search_path=public as $$ begin insert into public.portfolio_financial_snapshots(project_id,snapshot_date,budget_amount,planned_execution_amount,expenditure_amount,commitments_amount,notes) values(target_project_id,(payload->>'snapshot_date')::date,coalesce((payload->>'budget_amount')::numeric,0),coalesce((payload->>'planned_execution_amount')::numeric,0),coalesce((payload->>'expenditure_amount')::numeric,0),coalesce((payload->>'commitments_amount')::numeric,0),coalesce(payload->>'notes','')) on conflict(project_id,snapshot_date) do update set budget_amount=excluded.budget_amount,planned_execution_amount=excluded.planned_execution_amount,expenditure_amount=excluded.expenditure_amount,commitments_amount=excluded.commitments_amount,notes=excluded.notes; insert into public.portfolio_project_updates(project_id,report_date,physical_progress_pct,summary,achievements,bottlenecks,next_steps) values(target_project_id,coalesce((payload->>'report_date')::date,(payload->>'snapshot_date')::date),coalesce((payload->>'physical_progress_pct')::numeric,0),coalesce(payload->>'summary',''),coalesce(payload->>'achievements',''),coalesce(payload->>'bottlenecks',''),coalesce(payload->>'next_steps','')) on conflict(project_id,report_date) do update set physical_progress_pct=excluded.physical_progress_pct,summary=excluded.summary,achievements=excluded.achievements,bottlenecks=excluded.bottlenecks,next_steps=excluded.next_steps; if payload ? 'status' then update public.portfolio_projects set status=(payload->>'status')::public.portfolio_project_status,updated_at=now() where id=target_project_id; end if; end $$;
